config/routes.rb
OctopressAdmin::Application.routes.draw do
  root to: "posts#index"
  resources :posts do
    get 'generate_site', :on => :collection
  end  

  # get 'signup', to: 'users#new', as: 'signup' #uncomment to enable sign up functionality
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
end

app/models/post.rb
class Post
  YML = File.join(Rails.root,"config","config.yml")
  
  include ActiveAttr::Model
  
  #attr_accessor :name, :content, :date, :url
  
  attribute :id, :type => Integer
  attribute :name, :type => String
  attribute :content, :type => String
  attribute :published, :default => 0, :type => Integer
  attribute :year, :type => Integer
  attribute :month, :type => Integer
  attribute :day, :type => Integer
  attribute :url, :type => String
  # Layout params
  attribute :categories, :type => String
  attribute :tags, :type => String
  attribute :comments, :default => 1, :type => Integer
  attribute :rss, :default => 1, :type => Integer
  
  validates_presence_of :name, :content, :categories, :tags, :year, :month, :day
  
  def initialize(attributes = {})
    super
    Post.load_config
    @url = Post.load_path
    self.url = @url
  end
  
  def date
    [self.year, (sprintf '%02d', self.month), (sprintf '%02d', self.day)].join("-")
  end
  
  def self.all
    @posts = []
    Dir[File.join(@dir, "*.html")].each_with_index do |file, i|
      @posts << { id: i,
                  date: File.basename(file).scan(/\d+-/).join("/").gsub!(/-/,""),
                  title: File.basename(file).split(/- */, 4).last.capitalize.gsub!(/\.html/, "").gsub!(/-/, " "), 
                  url: [@dir, File.basename(file)].join("/"),
                  published: File.exists?([ @publish_path, 
                                             File.basename(file).scan(/\d+-/).join("/").gsub!(/-/,"").split("/"),
                                             File.basename(file).split(/- */, 4).last.gsub!(/\.html/, ""),
                                             "index.html"].join("/")) ? 1 : 0 }
    end
    return @posts
  end
  
  def self.find(id)
    posts = self.all
    posts.find do |p|
      if p[:id]  == id.to_i
        @post = Post.new
        @post.url = [@post.url, p[:url].gsub!(/(\/)+(\D*)/, "")].join("/")
        @post.id = p[:id].to_i
        @post.year = p[:date].split("/").first
        @post.month =  p[:date].split("/")[1]
        @post.day = p[:date].split("/").last
        @post.name = p[:title]
        Post.load(@post)
      end
    end
    return @post
  end
  
  
  def self.load(post)
    doc = Nokogiri::HTML(open(post.url))
    yaml_front_matter = doc.xpath("//p").text.split(/-{3}/)[1]
    layout = yaml_front_matter.scan(/layout:\s\w*/)[0].gsub(/layout:/, "")
    post.categories = yaml_front_matter.scan(/categories:\s\w*/)[0].gsub(/categories:/,"").strip!
    post.tags = yaml_front_matter.scan(/^-\W*+.*/).each {|t| t.gsub!(/-/,"").strip! }.join(", ")
    rss = yaml_front_matter.scan(/rss:\s\w*/)[0].gsub(/rss:/,"").strip!
    rss == "true" ? post.rss = 1 : post.rss = 0
    comments = yaml_front_matter.scan(/comments:\s\w*/)[0].gsub(/comments:/,"").strip!
    comments == "true" ? post.comments = 1 : post.comments = 0
    published = yaml_front_matter.scan(/published:\s\w*/)[0].gsub(/published:/,"").strip!
    published == "true" ? post.published = 1 : post.published = 0
    doc.xpath("//p[1]").first.remove #remove the yaml front matter incapsulated in <p> tag by default
    doc.children.each {|p| post.content = p} # cycle through remaining nodes
  end
  
  
  def save
    filename = "#{self.url}/#{self.date}-#{self.name.to_url}.html"
    unless File.exist?(filename)
      #puts "Creating new post: #{filename}"
      write(filename)
    end
  end
  
  
  def update_attributes(values)
    values.each { |k,v| self.send "#{k}=", v }
    temp_file = Tempfile.new("#{self.date}-#{self.name.to_url}.html")
    write(temp_file)
    FileUtils.mv(temp_file.path, self.url)
    new_file_name = "#{self.url.gsub(/\/{1}\d.*./, '')}/#{self.date}-#{self.name.to_url}.html"
    File.rename(self.url, new_file_name )
    self.url = new_file_name
  end
  
  def destroy
    #puts "Deleting post: #{self.url}"
    File.delete(self.url)
  end
  
  def self.generate_site
    path = @config[Rails.env]["relative_blog_path"]
    system "cd #{path} && rake generate"
  end
  
  def self.load_config(config=YML)
    @config = YAML.load_file(config)
  end
  
  def self.load_categories
     @categories = []
     [@config["categories"]].each { |category| category.each {|h| h.each {|k,v| @categories << v } }}
     return @categories
  end
  
  def self.load_path
    @dir = [@config[Rails.env]["relative_blog_path"], @config[Rails.env]["posts_path"]].join("/")
  end
  
  def self.published_path
    @publish_path = @config[Rails.env]["published_path"]
  end
  
  def self.load_default(arg)
    return @arg = @config["site"][arg]
  end
  
  private
    
    def write(filename)
      open(filename, 'w') do |post|
        post.puts "---"
        post.puts "layout: post"
        post.puts "title: \"#{self.name.gsub(/&/,'&amp;')}\""
        post.puts "date: #{self.date}"
        post.puts self.published == 1 ? "published: true" : "published: false"
        post.puts self.comments == 1 ? "comments: true" : "comments: false"
        post.puts self.rss == 1 ? "rss: true" : "rss: false"
        post.puts "categories: #{self.categories}"
        post.puts "tags:\n- #{self.tags.gsub(/,/, "\n-")}"
        post.puts "---"
        post.puts "\n"
        post.puts "#{self.content}"
      end
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize
  
  def index
    @posts = Post.all.paginate(:page => params[:page], :per_page => 10)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.valid?
        @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.valid?
        @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  def generate_site
    Post.delay.generate_site
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Generating website.' }
      format.json { head :no_content }
    end
  end
  
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<fieldset>
  <legend><%= controller.action_name.capitalize %> Post</legend>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <% if @post.year? && @post.month? && @post.day? %>
        <%= select_date Date.parse(@post.date), :order => [:year, :month, :day], :prefix => 'post', :use_month_numbers => true %>
      <% else %>
        <%= select_date Time.now, :order => [:year, :month, :day], :prefix => 'post', :use_month_numbers => true %>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'span7' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :categories, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :categories, Post.load_categories, :include_blank => true, :class => 'span1' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'span3' %>
      <span class="help-inline">Separeted by commas (eg: tag1, tag2, tag3)</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :published, :class => 'control-label' %>
    <div class='controls'>
      <%= f.check_box :published %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class='controls'>
      <%= f.check_box :comments %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rss, :class => 'control-label' %>
    <div class='controls'>
      <%= f.check_box :rss %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', posts_path, :class => 'btn' %>
  </div>
</fieldset>

app/views/posts/edit.html.erb
<%= form_for(@post, :url => { :action => "update" }, :html => { :class => 'form-horizontal', :method => "put" }) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th></th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post[:date] %></td>
        <td><%= link_to post[:title], post_path(post[:id]) %></td>
        <td><%= link_to 'Edit', edit_post_path(post[:id]), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Delete', post_path(post[:id]), confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @posts, :renderer => BootstrapPagination::Rails %>

<%= link_to 'New Post', new_post_path, :class => 'btn btn-primary' %> 
<%= link_to 'Generate Site', generate_site_posts_path, confirm: "This will generate the website according to the post published status in the yaml front matter.\n Do you want to continue?", :method => :get, :class => 'btn btn-primary btn-danger' %>

app/views/posts/new.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1><%= @post.name %> <br /><small>on <%= @post.date %> in <%= @post.categories %> | tagged <%= @post.tags %></small></h1> 
</div>
<p>
  <%= raw @post.content %>
</p>

<p>
Comments
<% if @post.comments == 1 %>
  <i class="icon-ok-circle"></i> 
<% else %>
  <i class="icon-ban-circle"></i> 
<% end %>
Rss
<% if @post.rss == 1 %>
  <i class="icon-ok-circle"></i> 
<% else %>
  <i class="icon-ban-circle"></i> 
<% end %> 
Published
<% if @post.published == 1 %>
  <i class="icon-ok-circle"></i> 
<% else %>
  <i class="icon-ban-circle"></i> 
<% end %>
</p>

<div class="form-actions">
  <%= link_to 'Back', posts_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_post_path(@post[:id]), :class => 'btn' %>
  <%= link_to 'Delete', post_path(@post[:id]), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>