config/routes.rb
OctopressAdmin::Application.routes.draw do
  root to: "posts#index"
  resources :posts do
    get 'generate_site', :on => :collection
  end  

  # get 'signup', to: 'users#new', as: 'signup' #uncomment to enable sign up functionality
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OctopressAdmin</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to @title, root_path, :class => 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <% if current_user %>
              Logged in as <%= current_user.email %>.
              <li><%= link_to "Log Out", logout_path %></li>
            <% else %>
              <li><%= link_to "Log In", login_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>
  
</div>
</body>
</html>